#!/bin/sh

TIME=timeTEXT
HOST=localhost
PORT=1234

GETTEXT="gettext -d timeTEXT_ui"

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog


	$DIALOG --inputbox "`$GETTEXT \"Enter Continent/City:\"`" 8 35 2> /tmp/input.$$

       	now1=$(export TZ=`cat /tmp/input.$$`;date)
	na=`cat /tmp/input.$$`

	MSG="`$GETTEXT \"Hello $na, your time now is:\"` \n\n$now1\\n\\n"
		$DIALOG --yesno "$MSG" 7 20 || end
