#!/bin/sh


export LANG=en.US.UTF-8


HOST=localhost
PORT=1234

FILE1=/tmp/main1
FILE2=/tmp/main2
ERROR=/tmp/main-err


MAIN="nc $HOST $PORT"
#!/bin/sh

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

$DIALOG --inputbox "Enter Continent/City:" 8 35 2> $FILE1 || end

###
if cat $FILE1 | $MAIN > $FILE2 2>$ERROR
then
zenity --info --text "`cat $FILE2`"
#else
# zenity --info --text "Error"
fi
###
